name: Release @nativescript/core to NPM

on:
  push:
    branches: [ 'master' ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: npm install

      - name: Generate Version
        working-directory: packages/core
        run: |
          echo NPM_TAG=next >> $GITHUB_ENV
          echo NPM_VERSION=$(node -e "console.log(require('./package.json').version);")-$NPM_TAG-$(date +"%m-%d-%Y")-$GITHUB_RUN_ID >> $GITHUB_ENV

      - name: Bump Version
        working-directory: packages/core
        run: npm version $NPM_VERSION

      - name: Build @nativescript/core
        run: npx nx run core:build

      - name: Publish @nativescript/core
        working-directory: dist/packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "Publishing @nativescript/core@$NPM_VERSION to NPM with tag $NPM_TAG..."
          npm publish nativescript-core-$NPM_VERSION.tgz --tag $NPM_TAG --dry-run
